// Auto-generated data file for BopomonCollection
// Source: bopomon_data_sample.csv

export const initialData = {
  monster_database: {
    setter: 'setMonsterDatabase',
    value: {
      content: [
        { bpm_codex_id: 10001, pinyin: 'yin3', rarity: 'common', traditional_character: '饮', hatch_status: 1, png_tcg_asset_fn: 'yin3 - beverage' },
        { bpm_codex_id: 10002, pinyin: 'cun1', rarity: 'common', traditional_character: '村', hatch_status: 1, png_tcg_asset_fn: 'cun1 - village' },
        { bpm_codex_id: 10003, pinyin: 'yun2', rarity: 'common', traditional_character: '云', hatch_status: 1, png_tcg_asset_fn: 'yun2 - cloud' },
        { bpm_codex_id: 10004, pinyin: 'lue4', rarity: 'common', traditional_character: '略', hatch_status: 1, png_tcg_asset_fn: 'lue4 - strategy' },
        { bpm_codex_id: 10005, pinyin: 'peng2', rarity: 'common', traditional_character: '朋', hatch_status: 1, png_tcg_asset_fn: 'peng2 - friend' },
        { bpm_codex_id: 10006, pinyin: 'chun1', rarity: 'common', traditional_character: '春', hatch_status: 1, png_tcg_asset_fn: 'chun1 - spring' },
        { bpm_codex_id: 10007, pinyin: 'tong1', rarity: 'common', traditional_character: '同', hatch_status: 1, png_tcg_asset_fn: 'tong1 - together' },
        { bpm_codex_id: 10008, pinyin: 'wen4', rarity: 'common', traditional_character: '问', hatch_status: 1, png_tcg_asset_fn: 'wen4 - ask' },
        { bpm_codex_id: 10009, pinyin: 'ying3', rarity: 'common', traditional_character: '影', hatch_status: 1, png_tcg_asset_fn: 'ying3 - shadow' },
        { bpm_codex_id: 10010, pinyin: 'an1', rarity: 'common', traditional_character: '安', hatch_status: 1, png_tcg_asset_fn: 'an1 - calm' },
        { bpm_codex_id: 10011, pinyin: 'guang1', rarity: 'common', traditional_character: '光', hatch_status: 1, png_tcg_asset_fn: 'guang1 - light' },
        { bpm_codex_id: 10012, pinyin: 'yin1', rarity: 'common', traditional_character: '音', hatch_status: 1, png_tcg_asset_fn: 'yin1 - music' },
        { bpm_codex_id: 10013, pinyin: 'chang3', rarity: 'common', traditional_character: '场', hatch_status: 1, png_tcg_asset_fn: 'chang3 - courtyard' },
        { bpm_codex_id: 10014, pinyin: 'nu2', rarity: 'common', traditional_character: '奴', hatch_status: 1, png_tcg_asset_fn: 'nu2 - servant' },
        { bpm_codex_id: 10015, pinyin: 'chan3', rarity: 'common', traditional_character: '产', hatch_status: 1, png_tcg_asset_fn: 'chan3 - resource' },
        { bpm_codex_id: 15, pinyin: 'lai2', rarity: 'common', traditional_character: '来', hatch_status: 1, png_tcg_asset_fn: 'lai2 - come' },
        { bpm_codex_id: 17, pinyin: 'da4', rarity: 'common', traditional_character: '大', hatch_status: 1, png_tcg_asset_fn: 'da4 - big' },
        { bpm_codex_id: 20, pinyin: 'guo2', rarity: 'common', traditional_character: '国', hatch_status: 1, png_tcg_asset_fn: 'guo2 - country' },
        { bpm_codex_id: 24, pinyin: 'shuo1', rarity: 'common', traditional_character: '说', hatch_status: 1, png_tcg_asset_fn: 'shuo1 - speak' },
        { bpm_codex_id: 25, pinyin: 'shi2', rarity: 'common', traditional_character: '时', hatch_status: 1, png_tcg_asset_fn: 'shi2 - time' },
        { bpm_codex_id: 28, pinyin: 'chu1', rarity: 'common', traditional_character: '出', hatch_status: 1, png_tcg_asset_fn: 'chu1 - out' },
        { bpm_codex_id: 29, pinyin: 'hui4', rarity: 'common', traditional_character: '会', hatch_status: 1, png_tcg_asset_fn: 'hui4 - conference' },
        { bpm_codex_id: 33, pinyin: 'dui4', rarity: 'common', traditional_character: '对', hatch_status: 1, png_tcg_asset_fn: 'dui4 - pair' },
        { bpm_codex_id: 34, pinyin: 'sheng1', rarity: 'common', traditional_character: '生', hatch_status: 1, png_tcg_asset_fn: 'sheng1 - birth' },
        { bpm_codex_id: 42, pinyin: 'xia4', rarity: 'common', traditional_character: '下', hatch_status: 1, png_tcg_asset_fn: 'xia4 - down' },
        { bpm_codex_id: 45, pinyin: 'nian2', rarity: 'common', traditional_character: '年', hatch_status: 1, png_tcg_asset_fn: 'nian2 - year' },
        { bpm_codex_id: 47, pinyin: 'fa4', rarity: 'common', traditional_character: '发', hatch_status: 1, png_tcg_asset_fn: 'fa4 - hair' },
        { bpm_codex_id: 52, pinyin: 'dao4', rarity: 'common', traditional_character: '道', hatch_status: 1, png_tcg_asset_fn: 'dao4 - path' },
        { bpm_codex_id: 60, pinyin: 'fang1', rarity: 'common', traditional_character: '方', hatch_status: 1, png_tcg_asset_fn: 'fang1 - square' },
        { bpm_codex_id: 62, pinyin: 'jing1', rarity: 'common', traditional_character: '经', hatch_status: 1, png_tcg_asset_fn: 'jing1 - scripture' },
        { bpm_codex_id: 66, pinyin: 'xue2', rarity: 'common', traditional_character: '学', hatch_status: 1, png_tcg_asset_fn: 'xue2 - learn' },
        { bpm_codex_id: 74, pinyin: 'mian4', rarity: 'common', traditional_character: '面', hatch_status: 1, png_tcg_asset_fn: 'mian4 - noodle' },
        { bpm_codex_id: 76, pinyin: 'kan4', rarity: 'common', traditional_character: '看', hatch_status: 1, png_tcg_asset_fn: 'kan4 - look' },
        { bpm_codex_id: 78, pinyin: 'tian1', rarity: 'common', traditional_character: '天', hatch_status: 1, png_tcg_asset_fn: 'tian1 - sky' },
        { bpm_codex_id: 83, pinyin: 'xiao3', rarity: 'common', traditional_character: '小', hatch_status: 1, png_tcg_asset_fn: 'xiao3 - small' },
        { bpm_codex_id: 90, pinyin: 'xin1', rarity: 'common', traditional_character: '心', hatch_status: 1, png_tcg_asset_fn: 'xin1 - heart' },
        { bpm_codex_id: 94, pinyin: 'kai1', rarity: 'common', traditional_character: '开', hatch_status: 1, png_tcg_asset_fn: 'kai1 - open' },
        { bpm_codex_id: 99, pinyin: 'xiang3', rarity: 'common', traditional_character: '想', hatch_status: 1, png_tcg_asset_fn: 'xiang3 - think' },
        { bpm_codex_id: 101, pinyin: 'ri4', rarity: 'common', traditional_character: '日', hatch_status: 1, png_tcg_asset_fn: 'ri4 - day' },
        { bpm_codex_id: 102, pinyin: 'jun1', rarity: 'common', traditional_character: '军', hatch_status: 1, png_tcg_asset_fn: 'jun1 - soldier' },
        { bpm_codex_id: 106, pinyin: 'li4', rarity: 'common', traditional_character: '力', hatch_status: 1, png_tcg_asset_fn: 'li4 - power' },
        { bpm_codex_id: 109, pinyin: 'chang2', rarity: 'common', traditional_character: '长', hatch_status: 1, png_tcg_asset_fn: 'chang2 - long' },
        { bpm_codex_id: 110, pinyin: 'ba3', rarity: 'common', traditional_character: '把', hatch_status: 1, png_tcg_asset_fn: 'ba3 - pull' },
        { bpm_codex_id: 111, pinyin: 'ji1', rarity: 'common', traditional_character: '机', hatch_status: 1, png_tcg_asset_fn: 'ji1 - machine' },
        { bpm_codex_id: 112, pinyin: 'shi2', rarity: 'common', traditional_character: '十', hatch_status: 1, png_tcg_asset_fn: 'shi2 - ten' },
        { bpm_codex_id: 118, pinyin: 'gong1', rarity: 'common', traditional_character: '工', hatch_status: 1, png_tcg_asset_fn: 'gong1 - work' },
        { bpm_codex_id: 119, pinyin: 'shi3', rarity: 'common', traditional_character: '使', hatch_status: 1, png_tcg_asset_fn: 'shi3 - messenger' },
        { bpm_codex_id: 125, pinyin: 'san1', rarity: 'common', traditional_character: '三', hatch_status: 1, png_tcg_asset_fn: 'san1 - three' },
        { bpm_codex_id: 127, pinyin: 'guan1', rarity: 'common', traditional_character: '关', hatch_status: 1, png_tcg_asset_fn: 'guan1 - close' },
        { bpm_codex_id: 128, pinyin: 'dian3', rarity: 'common', traditional_character: '点', hatch_status: 1, png_tcg_asset_fn: 'dian3 - dot' },
        { bpm_codex_id: 134, pinyin: 'gao1', rarity: 'common', traditional_character: '高', hatch_status: 1, png_tcg_asset_fn: 'gao1 - high' },
        { bpm_codex_id: 140, pinyin: 'zhong4', rarity: 'common', traditional_character: '重', hatch_status: 1, png_tcg_asset_fn: 'zhong4 - heavy' },
        { bpm_codex_id: 143, pinyin: 'shou3', rarity: 'common', traditional_character: '手', hatch_status: 1, png_tcg_asset_fn: 'shou3 - hand' },
        { bpm_codex_id: 147, pinyin: 'tou2', rarity: 'common', traditional_character: '头', hatch_status: 1, png_tcg_asset_fn: 'tou2 - head' },
        { bpm_codex_id: 148, pinyin: 'wen2', rarity: 'common', traditional_character: '文', hatch_status: 1, png_tcg_asset_fn: 'wen2 - culture' },
        { bpm_codex_id: 149, pinyin: 'ti3', rarity: 'common', traditional_character: '体', hatch_status: 1, png_tcg_asset_fn: 'ti3 - body' },
        { bpm_codex_id: 151, pinyin: 'mei3', rarity: 'common', traditional_character: '美', hatch_status: 1, png_tcg_asset_fn: 'mei3 - beautiful' },
        { bpm_codex_id: 154, pinyin: 'bei4', rarity: 'common', traditional_character: '被', hatch_status: 1, png_tcg_asset_fn: 'bei4 - blanket' },
        { bpm_codex_id: 165, pinyin: 'guo3', rarity: 'common', traditional_character: '果', hatch_status: 1, png_tcg_asset_fn: 'guo3 - fruit' },
        { bpm_codex_id: 169, pinyin: 'yue4', rarity: 'common', traditional_character: '月', hatch_status: 1, png_tcg_asset_fn: 'yue4 - moon' },
        { bpm_codex_id: 176, pinyin: 'xin4', rarity: 'common', traditional_character: '信', hatch_status: 1, png_tcg_asset_fn: 'xin4 - letter' },
        { bpm_codex_id: 179, pinyin: 'lao3', rarity: 'common', traditional_character: '老', hatch_status: 1, png_tcg_asset_fn: 'lao3 - old' },
        { bpm_codex_id: 189, pinyin: 'hai3', rarity: 'common', traditional_character: '海', hatch_status: 1, png_tcg_asset_fn: 'hai3 - ocean' },
        { bpm_codex_id: 191, pinyin: 'jiao1', rarity: 'common', traditional_character: '教', hatch_status: 1, png_tcg_asset_fn: 'jiao1 - teach' },
        { bpm_codex_id: 194, pinyin: 'dong1', rarity: 'common', traditional_character: '东', hatch_status: 1, png_tcg_asset_fn: 'dong1 - east' },
      ],
      metadata: {
        source: 'bopomon_data_sample.csv',
        generated_at: '2025-01-13T00:00:00.000Z'
      }
    }
  }
}
