import React from 'react'
import SandtroutHarness from './SandtroutHarness.jsx'

// ============================================
// CONFIGURE YOUR COMPONENT HERE
// ============================================

// 1. Import your Sandtrout component
import BopomonCollection from './components/BopomonCollection/BopomonCollection.jsx'

// 2. Import the component's initial data (generated by packager)
import { initialData } from './components/BopomonCollection/data.js'

// 3. Set the app title (shown in header)
const APP_TITLE = 'Bopomon Collection'

// 4. Pass the component and data to the harness
export default function App() {
  return (
    <SandtroutHarness 
      component={BopomonCollection}
      initialData={initialData}
      title={APP_TITLE}
    />
  )
}